# 配置端口
server:
  port: 8080

# 配置mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 设置上传图片大小限制
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  # redis配置
  redis:
    host: 43.140.200.189
    port: 6379
    password: redis456

# 配置mybatis plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    field-strategy: 1
    db-config:
      id-type: auto
      # table-prefix: sg_
      logic-delete-field: delFlag  # 配置@TableLogic使用
      logic-delete-value: 1
      logic-not-delete-value: 0

# 配置七牛云
oss:
  accessKey: Qj1LEeESxcMN4VKPa_kc1Mg76em5KB91-86oj6TO
  secretKey: l8WXGKVJAGKqvHd7ulFn560fB5Fd9lC7fl0REZt2
  bucket: fengxiuyang
  domain: "http://rirmohhkr.hb-bkt.clouddn.com/"
  failedDomain: "www"


