# 配置端口
server:
  port: 8080

# 配置mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai
    username: root
    password: root456
    driver-class-name: com.mysql.cj.jdbc.Driver

# 设置上传图片大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 配置mybatis plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb_
      logic-delete-field: isDelete  # 配置@TableLogic使用
      logic-delete-value: 1
      logic-not-delete-value: 0




